### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tanakaedu** [tanakaedu/ToriBomb2017#1]
- [x] 仮画面の作成
- [x] Androidにビルド
- [x] シーンの作成
- [x] スコアの実装
  - [x] 文字表示
  - [x] GameControllerにスコア機能を持たせる
- [x] 卵の生成
- [x] 爆弾
- [x] 爆風で卵を孵す
- [x] 爆風で誘爆
- [x] スコア調整
- [x] 獲得スコア表示
- [x] ハイスコアの実装
  - [x] ハイスコアをゲームオーバーとタイトルに表示
  - [x] 変数を宣言
  - [x] 読み込みと書き出し
    - https://docs.unity3d.com/jp/current/ScriptReference/PlayerPrefs.html
# 獲得スコア表示
- [x] 画像の用意
- [x] 倍率(イメージ)
- [x] 基礎点表示(テキスト)
- [x] 表示

# 爆風で誘爆
- [x] 爆発を判定して、誘爆
- [x] 誘爆数を定義
- [x] 誘爆数でスコアを倍

# 爆風で卵を孵す
- [x] ひよこを作成
  - Rigidbody2D、コライダーはそのまま
  - 当たり判定をBoxCollider2D
- [x] ひよこのアニメを作成
  - 空中では万歳
  - 着地したら歩きに切り替える
- [x] 卵を孵す
  - 卵を消す
  - その場所にひよこを出現
  - 座標によって、左右をフリップ
- [x] 着地判定
- [x] 着地したら歩く
- [x] 画面外に出たら消す
  - http://tsubakit1.hateblo.jp/entry/20131007/1381156232

# 爆弾
- [x] アニメの作成
  - [x] アニメの作成
  - [x] 爆発に切り替わる時に、タグを変更
  - [x] 爆発が終わったら消す
- [x] 当たり判定など、プレハブの構築
- [x] クリックした場所に出現
- [x] 爆弾の出現上限を決める
- [x] ゲームオーバーになったら、判定とアニメを停止する

# シーンの作成
シーンは game 一つを使いまわす。

- [x] ゲームを管理する永続ゲームオブジェクト(GameController)の作成
- [x] ゲームを管理するスクリプト GameController.cs の作成
- [x] タイトル、ゲーム、ゲームオーバーの定義を仮表示
- [x] 状態遷移の作成

# 卵の生成
- [x] 卵のアニメ作成
  -   ##通常(egg)と割れ(miss)。フラグmissのtrue/falseで切り替え
- [x] 卵の生成
- [x] 落下したら割れる
- [x] 割れたらゲームオーバーへ
